### ISSUE TITLE
IDL file comment issues

### ISSUE THREAD

**Issue by 4brunu** [dropbox/djinni#231] opened 2016-05-18 11:05 UTC
Hi,

I have some issues with comments in the IDL file.

Djinni return some error, when parsing comments at the end of files, enum's, records or interfaces.

Here is an IDL file example with comments and the respective error.

```
# Works
my_enum = enum {
    option1;
    # Error - string matching regex `[A-Za-z_][A-Za-z_0-9]*' expected but `}' found
}
#Error - string matching regex `[A-Za-z_][A-Za-z_0-9]*' expected but end of source found
```

This is not a critical issue, but I want to report it because I don't know if it's a known issue.

Thanks

**Comment by j4cbo** [comment] 2016-05-18 14:03
This is known - closing as duplicate of #53

**Closed by j4cbo** 2016-05-18 14:03 UTC
