### ISSUE TITLE
cpp-extended-record-include-prefix is not always honoured 

### ISSUE THREAD

**Issue by milch** [dropbox/djinni#269] opened 2016-08-09 15:39 UTC
Consider the following example: 

```
request = record +c {
    method : string;
    url : string;
    // etc... 
}

response = record +c {
    request : request;
    status_code : i32;
    // etc...
}
```

The generated code for `response_base.hpp` will be using `#include "request.hpp"` even when I use the flag `--cpp-extended-record-include-prefix "extended/"`.

**Comment by artwyman** [comment] 2016-08-10 02:51
Confirmed this is a bug.  Seems to be specific to the case of an extended record being included in another record.

**Comment by artwyman** [comment] 2016-08-11 22:06
Fixed in 6c869e1

**Closed by artwyman** 2016-08-11 22:06 UTC
Labels: bug
