### ISSUE TITLE
Local reference overflow crash on Android ART

### ISSUE THREAD

**Issue by izacus** [dropbox/djinni#218] opened 2016-03-21 20:16 UTC
We've hit an interesting issue when transporting larger amount of objects in lists (or maps or other datastructures) over JNI using Djinni.

It seems Djinni support library exhausts the number of allowed local JNI references and crashes with ```local reference table overflow (max=512)``` error. The local reference table is hard-coded to 512 entries with ART and cannot be changed (methods like `EnsureLocalCapacity` have the same limitation).  Most of the objects being referenced are weak references. 

This happens if we use records or interfaces as long as they are non-primitive objects.

I'm attaching the djinni example ZIP with the sample modified in a way that causes the crash, full stack trace is:

```
03-21 21:00:02.795 1932-1932/com.dropbox.textsort A/art: art/runtime/indirect_reference_table.cc:98] JNI ERROR (app bug): local reference table overflow (max=512)
03-21 21:00:02.795 1932-1932/com.dropbox.textsort A/art: art/runtime/indirect_reference_table.cc:98] local reference table dump:
03-21 21:00:02.795 1932-1932/com.dropbox.textsort A/art: art/runtime/indirect_reference_table.cc:98]   Last 10 entries (of 511):
03-21 21:00:02.795 1932-1932/com.dropbox.textsort A/art: art/runtime/indirect_reference_table.cc:98]       510: 0x12cf8bc0 java.lang.ref.WeakReference
03-21 21:00:02.795 1932-1932/com.dropbox.textsort A/art: art/runtime/indirect_reference_table.cc:98]       509: 0x12cf8b80 java.lang.ref.WeakReference
03-21 21:00:02.795 1932-1932/com.dropbox.textsort A/art: art/runtime/indirect_reference_table.cc:98]       508: 0x12cf8b40 java.lang.ref.WeakReference
03-21 21:00:02.795 1932-1932/com.dropbox.textsort A/art: art/runtime/indirect_reference_table.cc:98]       507: 0x12cf8b00 java.lang.ref.WeakReference
03-21 21:00:02.795 1932-1932/com.dropbox.textsort A/art: art/runtime/indirect_reference_table.cc:98]       506: 0x12cf8ac0 java.lang.ref.WeakReference
03-21 21:00:02.795 1932-1932/com.dropbox.textsort A/art: art/runtime/indirect_reference_table.cc:98]       505: 0x12cf8a80 java.lang.ref.WeakReference
03-21 21:00:02.795 1932-1932/com.dropbox.textsort A/art: art/runtime/indirect_reference_table.cc:98]       504: 0x12cf8a40 java.lang.ref.WeakReference
03-21 21:00:02.795 1932-1932/com.dropbox.textsort A/art: art/runtime/indirect_reference_table.cc:98]       503: 0x12cf8a00 java.lang.ref.WeakReference
03-21 21:00:02.795 1932-1932/com.dropbox.textsort A/art: art/runtime/indirect_reference_table.cc:98]       502: 0x12cf89c0 java.lang.ref.WeakReference
03-21 21:00:02.795 1932-1932/com.dropbox.textsort A/art: art/runtime/indirect_reference_table.cc:98]       501: 0x12cf8980 java.lang.ref.WeakReference
03-21 21:00:02.795 1932-1932/com.dropbox.textsort A/art: art/runtime/indirect_reference_table.cc:98]   Summary:
03-21 21:00:02.795 1932-1932/com.dropbox.textsort A/art: art/runtime/indirect_reference_table.cc:98]         2 of java.lang.Class (2 unique instances)
03-21 21:00:02.795 1932-1932/com.dropbox.textsort A/art: art/runtime/indirect_reference_table.cc:98]         1 of java.util.ArrayList
03-21 21:00:02.795 1932-1932/com.dropbox.textsort A/art: art/runtime/indirect_reference_table.cc:98]         3 of java.lang.String (3 unique instances)
03-21 21:00:02.795 1932-1932/com.dropbox.textsort A/art: art/runtime/indirect_reference_table.cc:98]       504 of java.lang.ref.WeakReference (504 unique instances)
03-21 21:00:02.795 1932-1932/com.dropbox.textsort A/art: art/runtime/indirect_reference_table.cc:98]         1 of java.lang.String[] (3 elements)
03-21 21:00:02.795 1932-1932/com.dropbox.textsort A/art: art/runtime/indirect_reference_table.cc:98]
```

Any ideas on how to fix or work around this issue? Limiting calls in a way to avoid this issue is hugely impractical, since we're transporting objects from an outside (file) source that may legitimately have a tree of objects that go over that limit.

[djinni-sample.zip](https://github.com/dropbox/djinni/files/183032/djinni-sample.zip)

**Comment by artwyman** [comment] 2016-03-21 21:01
Thanks for reporting.  This kind of leak can likely only be addressed in the Djinni support library.  I haven't  had time to look into the example yet, but if the issue is with with long lists, I'd suspect one of two root causes.  If you say this can be reproduced using records rather than interfaces, though, I wouldn't expect WeakReference to be involved in the record case, since it's used for the interface proxy cache.

Root cause guess 1 is that Djinni has a bug and is never releasing some of its local references.  That kind of bug can be hidden since local refs are automatically purged on a return to Java, but Djinni tries to always free them immediately since not all code will return to Java quickly.

Root cause guess 2 is that Djinni isn't outright leaking anything, but is freeing things for the whole list after it's marshalled, but that the list is simply so long that it uses more than 512 local references to represent all of the objects in the list.  That's not correct behavior either, since it should always be possible to clean up local references agressively after marshaling each object in a list.  For instance, the proxy cache will hold on to long-term references to a WeakReference, which won't be freed until the last shared_ptr goes away in C++, but those long-term references should be Global not Local, so shouldn't cause this kind of overflow.

Figuring out which of those is going on will take some investigation into the Djinni code.  It might take me a while to have time to do that.  I wonder if @j4cbo might want to take a look, given the proxy cache is potentially implicated here.  I welcome anyone else who wants to dig into this debugging exercise too

I don't know the structure of your app, but I suspect the only possible workaround would be to use shorter lists, perhaps by paging.

**Comment by j4cbo** [comment] 2016-03-21 21:06
I can take a look later on this week.

**Comment by artwyman** [comment] 2016-03-21 21:32
Awesome, thanks!

**Comment by artwyman** [comment] 2016-04-12 05:47
@j4cbo Any progress on this?

**Comment by yinyinnie** [comment] 2016-05-12 02:12
@j4cbo @artwyman How about this problem?

**Comment by j4cbo** [comment] 2016-05-17 17:03
I've reproduced this locally and am working on tracking it down.

**Closed** 2016-05-17 19:32 UTC
Labels: bug
