### ISSUE TITLE
Syntax error on trailing comments in interfaces

### ISSUE THREAD

**Issue by jefftrull** [dropbox/djinni#173] opened 2015-12-13 00:59 UTC
It looks like the .djinni file parser gets confused when an interface definition has an embedded comment at the end.  For example:

```
# Test case for comments at the end of interfaces
good_if = interface +c {
    method(i : i32) : i32;
}

bad_if = interface +c {
    method(i : i32) : i32;
    # This otherwise identical interface has a trailing comment
}
```

The error produced is 
```
test.djinni (9.1): `const' expected but `}' found
```

**Comment by artwyman** [comment] 2015-12-13 01:04
That's a manifestation of a broader issue, or rather a missing feature.  Djinni doesn't support comments.  It supports documentation, which gets propagated into the generated code.  Documentation has to come before some declaration it can be attached to, which is why the trailing comment doesn't work.  You'll see similar issues if you try to put a comment before an import of another Djinni file, for instance.

That's an explanation not a defense.  We should definitely support generalized comments, whether propagated or not.  A proposal which has circulated internally at Dropbox has been to support a separate syntax (// or /* */) for true "comments" which get treated like whitespace by the parser and discared, while reserving # for documentation.

**Comment by jefftrull** [comment] 2015-12-13 01:25
Thanks for the prompt response!  That makes sense.

(my use case is for commenting out a method I intend to add later)

**Comment by j4cbo** [comment] 2015-12-14 17:44
Trailing documentation would be useful too, but comments are definitely more important.

**Comment by artwyman** [comment] 2016-01-06 23:12
Closing as duplicate of #53

**Closed by artwyman** 2016-01-06 23:12 UTC
Labels: enhancement
